version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-semestral
    environment:
      MYSQL_ROOT_PASSWORD: heslo
      MYSQL_DATABASE: semestral
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-semestral
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql-data: